# render.yaml (자동 배포 설정)
services:
  - type: web
    name: bybit-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run dashboard.py --server.address 0.0.0.0 --server.port 10000
    envVars:
      - key: STREAMLIT_SERVER_PORT
        value: 10000
      - key: STREAMLIT_SERVER_ADDRESS  
        value: 0.0.0.0
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
